### PR TITLE
Lower UID/GID

### LINKED ISSUE #6: uid/gid 99999 problem with user namespace remapping enabled
In setups with user namespace remapping enabled there's a default UID and GID range of 65536 available in the container namespace. The base image has hardcoded UID and GID 99999, when pulling this image on systems with enabled user namespace remapping, docker gives the error below:

    failed to register layer: Error processing tar file(exit status 1): Container ID 99999 cannot be mapped to a host ID

It is possible to configure  larger UID and GID ranges on linux side but since 65536 is the default value it would be nicer to move the hardcoded IDs to something below 65536 to make standard setups happy again. Is that possible?

Thanks

### PR DESCRIPTION
**Pull request by robbyoconnor**
Lowering the UID/GID to 65533.

Fixes #6

### CODE REVIEW

**Comment by sampaiodiego** [comment]
could this cause issues to people who are using a volume and saving upload files to file system?

**Comment by robbyoconnor** [comment]
> could this cause issues to people who are using a volume and saving upload files to file system?

Nothing that a simple `chown` operation can't fix.

**Comment by geekgonecrazy** [comment]
@sampaiodiego maybe..  I kind of personally hate that we are manually specifying a uid/guid to begin with.  

I haven't push the base yet.. 

If we want to be in alignment with the official image we could just the uid/gid all together

**Comment by robbyoconnor** [comment]
> @sampaiodiego maybe.. I kind of personally hate that we are manually specifying a uid/guid to begin with.

I personally did it so to not conflict with system uids. 

Most normal user ids start with 1000 by default, and I don't know about you, but I don't want uploaded files owned by users on the server...

**Pull request merged**
